image:
  repository: "986397386508.dkr.ecr.eu-north-1.amazonaws.com/lesson-7-ecr"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

env:
  DJANGO_SETTINGS_MODULE: "app.settings"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"
  DJANGO_DEBUG: 1
  DJANGO_SECRET_KEY: "dev-secret-key"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
